ROOT="/home/ci/tests/otg_uhd_automation"
SYSTEMTESTPATH=ROOT+"/tests/systemTest"
FPPATH=ROOT+"/fp"
RELEASEINFOURL = "https://raw.githubusercontent.com/open-traffic-generator/ixia-c/main/docs/releases.md"
DEPLOYMENTFILEPATH = ROOT+"/deployment"
MAINLOGFILE=ROOT+"/run.log"
HISTORYFILE=ROOT+"/history.txt"
